repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        args: [--show-error-codes]
        name: mypy check
        files: parzen_estimator
  - repo: https://github.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8 check
        files: parzen_estimator/
        additional_dependencies:
          - flake8-import-order
      - id: flake8
        name: flake8 for test files
        files: test/
